version: '3.3'

services:

  db:
    image: postgres
    restart: always
  web:
    restart: always
    build: .
    command: ["./bin/docker_start.sh"]
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
